# ── Aplicación ────────────────────────────────────────────────────────
spring.application.name=bookstore

# ── Base de datos ─────────────────────────────────────────────────────
spring.datasource.url=jdbc:postgresql://localhost:5432/bookstore
spring.datasource.username=bookstore
spring.datasource.password=bookstore
spring.datasource.driver-class-name=org.postgresql.Driver

# ── JPA / Hibernate ───────────────────────────────────────────────────
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

# ── Flyway ────────────────────────────────────────────────────────────
spring.flyway.enabled=false
spring.flyway.locations=classpath:db/migration
spring.flyway.url=jdbc:postgresql://127.0.0.1:5432/bookstore
spring.flyway.user=bookstore
spring.flyway.password=bookstore

# ── RabbitMQ ──────────────────────────────────────────────────────────
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# ── Actuator ──────────────────────────────────────────────────────────
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# ── Logging ───────────────────────────────────────────────────────────
logging.level.com.geovannycode=DEBUG
logging.level.org.flywaydb=DEBUG
